name: ponder-dev
channels:
  - conda-forge
dependencies:
 - scikit-learn=0.20.0
 - pandas=0.23.4
 - numpy=1.15.2
 - codecov
 - coverage
 - flake8
 - pytest
 - sphinx
 - ipython
 - matplotlib
 - numpydoc
 - sphinx_rtd_theme
 - pip:
   - sphinx-copybutton
